spring:
  application:
    name: service-feign

eureka:
  peer1:
    hostname: server1
    port: 8761
  peer2:
    hostname: server2
    port: 8762
  peer3:
    hostname: server3
    port: 8763

server:
  servlet:
    context-path: /feign
