server:
  port: 8762

eureka:
  instance:
    hostname: ${eureka.peer2.hostname}

  client:
#    register-with-eureka: false
#    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.peer1.hostname}:${eureka.peer1.port}/eureka/,http://${eureka.peer2.hostname}:${eureka.peer2.port}/eureka/,http://${eureka.peer3.hostname}:${eureka.peer3.port}/eureka/
