# https://www.jianshu.com/p/8f4903be43a4 #
# https://www.jianshu.com/u/8fa6bf5f8bd9 #
spring:
  profiles:
    active: peer3

  application:
    name: eureka-server

eureka:
  peer1:
#    hostname: 47.111.142.100
    hostname: 192.168.140.130
    port: 8761
  peer2:
#    hostname: 47.111.142.100
    hostname: 192.168.140.130
    port: 8762
  peer3:
#    hostname: 47.111.142.100
    hostname: 192.168.140.130
    port: 8763

  server:
    # 定义renews 和renews threshold的比值
    #    renewal-percent-threshold: 0.49
    # 自我保护模式 true 开启 false 关闭
    enable-self-preservation: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
#    health:
#      # 查看eureka服务健康详细信息
#      enabled: true
#      roles: ACTUATOR
#      show-details: always

#server:
#  undertow:
#    direct-buffers: true
#    io-threads: 5
#    worker-threads: 20
